
/**
 * DeckRunner.java 
 *
 * @author: Jake Imyak
 * BlackJack Project
 * 
 * Brief Program Description:
 * Runs the Deck class to show that all methods of it work properly.
 *
 */

public class DeckRunner 
{
   public static void main(String[] args)
   {
       Deck deck = new Deck();
       System.out.println(deck);
       deck.shuffle();
       System.out.println(deck);
       System.out.println("Card 15: " + deck.getCard(15));
       System.out.println(deck);
       System.out.println("Top Card: " + deck.getTopCard());
       System.out.println(deck);
   }
}
/**
 * OUTPUT
 * [The card is a Ace of Hearts (value =  1), The card is a Ace of Spades (value =  1), The card is a Ace of Clubs (value =  1), The card is a Ace of Diamonds (value =  1), The card is a Two of Hearts (value =  2), The card is a Two of Spades (value =  2), The card is a Two of Clubs (value =  2), The card is a Two of Diamonds (value =  2), The card is a Three of Hearts (value =  3), The card is a Three of Spades (value =  3), The card is a Three of Clubs (value =  3), The card is a Three of Diamonds (value =  3), The card is a Four of Hearts (value =  4), The card is a Four of Spades (value =  4), The card is a Four of Clubs (value =  4), The card is a Four of Diamonds (value =  4), The card is a Five of Hearts (value =  5), The card is a Five of Spades (value =  5), The card is a Five of Clubs (value =  5), The card is a Five of Diamonds (value =  5), The card is a Six of Hearts (value =  6), The card is a Six of Spades (value =  6), The card is a Six of Clubs (value =  6), The card is a Six of Diamonds (value =  6), The card is a Seven of Hearts (value =  7), The card is a Seven of Spades (value =  7), The card is a Seven of Clubs (value =  7), The card is a Seven of Diamonds (value =  7), The card is a Eight of Hearts (value =  8), The card is a Eight of Spades (value =  8), The card is a Eight of Clubs (value =  8), The card is a Eight of Diamonds (value =  8), The card is a Nine of Hearts (value =  9), The card is a Nine of Spades (value =  9), The card is a Nine of Clubs (value =  9), The card is a Nine of Diamonds (value =  9), The card is a Ten of Hearts (value =  10), The card is a Ten of Spades (value =  10), The card is a Ten of Clubs (value =  10), The card is a Ten of Diamonds (value =  10), The card is a Jack of Hearts (value =  10), The card is a Jack of Spades (value =  10), The card is a Jack of Clubs (value =  10), The card is a Jack of Diamonds (value =  10), The card is a Queen of Hearts (value =  10), The card is a Queen of Spades (value =  10), The card is a Queen of Clubs (value =  10), The card is a Queen of Diamonds (value =  10), The card is a King of Hearts (value =  10), The card is a King of Spades (value =  10), The card is a King of Clubs (value =  10), The card is a King of Diamonds (value =  10)]
 * [The card is a Five of Hearts (value =  5), The card is a Three of Hearts (value =  3), The card is a Five of Clubs (value =  5), The card is a King of Spades (value =  10), The card is a Four of Clubs (value =  4), The card is a Two of Diamonds (value =  2), The card is a Eight of Spades (value =  8), The card is a Ace of Spades (value =  1), The card is a Five of Diamonds (value =  5), The card is a Four of Spades (value =  4), The card is a Six of Diamonds (value =  6), The card is a King of Clubs (value =  10), The card is a Jack of Diamonds (value =  10), The card is a Ten of Clubs (value =  10), The card is a Ten of Diamonds (value =  10), The card is a Queen of Diamonds (value =  10), The card is a Jack of Spades (value =  10), The card is a Seven of Spades (value =  7), The card is a Six of Clubs (value =  6), The card is a Seven of Diamonds (value =  7), The card is a Jack of Hearts (value =  10), The card is a Eight of Diamonds (value =  8), The card is a Ten of Spades (value =  10), The card is a King of Diamonds (value =  10), The card is a Two of Spades (value =  2), The card is a Ace of Hearts (value =  1), The card is a Three of Clubs (value =  3), The card is a Nine of Diamonds (value =  9), The card is a Six of Hearts (value =  6), The card is a Three of Spades (value =  3), The card is a Nine of Clubs (value =  9), The card is a Two of Clubs (value =  2), The card is a Ace of Diamonds (value =  1), The card is a Queen of Hearts (value =  10), The card is a Nine of Spades (value =  9), The card is a Two of Hearts (value =  2), The card is a Ace of Clubs (value =  1), The card is a Jack of Clubs (value =  10), The card is a Eight of Hearts (value =  8), The card is a Three of Diamonds (value =  3), The card is a Six of Spades (value =  6), The card is a Eight of Clubs (value =  8), The card is a Seven of Hearts (value =  7), The card is a Nine of Hearts (value =  9), The card is a Four of Hearts (value =  4), The card is a Queen of Clubs (value =  10), The card is a Five of Spades (value =  5), The card is a Ten of Hearts (value =  10), The card is a Queen of Spades (value =  10), The card is a King of Hearts (value =  10), The card is a Seven of Clubs (value =  7), The card is a Four of Diamonds (value =  4)]
 * Card 15: The card is a Ten of Diamonds (value =  10)
 * [The card is a Five of Hearts (value =  5), The card is a Three of Hearts (value =  3), The card is a Five of Clubs (value =  5), The card is a King of Spades (value =  10), The card is a Four of Clubs (value =  4), The card is a Two of Diamonds (value =  2), The card is a Eight of Spades (value =  8), The card is a Ace of Spades (value =  1), The card is a Five of Diamonds (value =  5), The card is a Four of Spades (value =  4), The card is a Six of Diamonds (value =  6), The card is a King of Clubs (value =  10), The card is a Jack of Diamonds (value =  10), The card is a Ten of Clubs (value =  10), The card is a Queen of Diamonds (value =  10), The card is a Jack of Spades (value =  10), The card is a Seven of Spades (value =  7), The card is a Six of Clubs (value =  6), The card is a Seven of Diamonds (value =  7), The card is a Jack of Hearts (value =  10), The card is a Eight of Diamonds (value =  8), The card is a Ten of Spades (value =  10), The card is a King of Diamonds (value =  10), The card is a Two of Spades (value =  2), The card is a Ace of Hearts (value =  1), The card is a Three of Clubs (value =  3), The card is a Nine of Diamonds (value =  9), The card is a Six of Hearts (value =  6), The card is a Three of Spades (value =  3), The card is a Nine of Clubs (value =  9), The card is a Two of Clubs (value =  2), The card is a Ace of Diamonds (value =  1), The card is a Queen of Hearts (value =  10), The card is a Nine of Spades (value =  9), The card is a Two of Hearts (value =  2), The card is a Ace of Clubs (value =  1), The card is a Jack of Clubs (value =  10), The card is a Eight of Hearts (value =  8), The card is a Three of Diamonds (value =  3), The card is a Six of Spades (value =  6), The card is a Eight of Clubs (value =  8), The card is a Seven of Hearts (value =  7), The card is a Nine of Hearts (value =  9), The card is a Four of Hearts (value =  4), The card is a Queen of Clubs (value =  10), The card is a Five of Spades (value =  5), The card is a Ten of Hearts (value =  10), The card is a Queen of Spades (value =  10), The card is a King of Hearts (value =  10), The card is a Seven of Clubs (value =  7), The card is a Four of Diamonds (value =  4)]
 * Top Card: The card is a Five of Hearts (value =  5)
 * [The card is a Three of Hearts (value =  3), The card is a Five of Clubs (value =  5), The card is a King of Spades (value =  10), The card is a Four of Clubs (value =  4), The card is a Two of Diamonds (value =  2), The card is a Eight of Spades (value =  8), The card is a Ace of Spades (value =  1), The card is a Five of Diamonds (value =  5), The card is a Four of Spades (value =  4), The card is a Six of Diamonds (value =  6), The card is a King of Clubs (value =  10), The card is a Jack of Diamonds (value =  10), The card is a Ten of Clubs (value =  10), The card is a Queen of Diamonds (value =  10), The card is a Jack of Spades (value =  10), The card is a Seven of Spades (value =  7), The card is a Six of Clubs (value =  6), The card is a Seven of Diamonds (value =  7), The card is a Jack of Hearts (value =  10), The card is a Eight of Diamonds (value =  8), The card is a Ten of Spades (value =  10), The card is a King of Diamonds (value =  10), The card is a Two of Spades (value =  2), The card is a Ace of Hearts (value =  1), The card is a Three of Clubs (value =  3), The card is a Nine of Diamonds (value =  9), The card is a Six of Hearts (value =  6), The card is a Three of Spades (value =  3), The card is a Nine of Clubs (value =  9), The card is a Two of Clubs (value =  2), The card is a Ace of Diamonds (value =  1), The card is a Queen of Hearts (value =  10), The card is a Nine of Spades (value =  9), The card is a Two of Hearts (value =  2), The card is a Ace of Clubs (value =  1), The card is a Jack of Clubs (value =  10), The card is a Eight of Hearts (value =  8), The card is a Three of Diamonds (value =  3), The card is a Six of Spades (value =  6), The card is a Eight of Clubs (value =  8), The card is a Seven of Hearts (value =  7), The card is a Nine of Hearts (value =  9), The card is a Four of Hearts (value =  4), The card is a Queen of Clubs (value =  10), The card is a Five of Spades (value =  5), The card is a Ten of Hearts (value =  10), The card is a Queen of Spades (value =  10), The card is a King of Hearts (value =  10), The card is a Seven of Clubs (value =  7), The card is a Four of Diamonds (value =  4)]
 * 
 */